server:
  host: "0.0.0.0"
  port: 8080
  media_root: "./media"
  allowed_origins:
    - "http://localhost:8080"
    - "http://localhost:8081"
    - "http://127.0.0.1:8080"
    - "http://127.0.0.1:8081"
    - "http://192.168.1.50:8081"
    - "http://192.168.1.50:8080"
database:
  path: "./data/aetherstream.db"
auth:
  secret: "this-is-a-test-secret-32-chars-long"
  token_ttl: 24
swiftflow:
  api_key: ""
  base_url: ""
